---
title: "Hand vs. Mod Analysis"
author: "Michelle Bang"
date: "5/31/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
new_df <- read.table(file = "new_m_data.tsv",
                              header = TRUE,
                              sep = '\t')


old_df <- read.table(file = "old_df.tsv",
                              header = TRUE,
                              sep = '\t')

fem_df <- read.table(file = "female_data.tsv",
                              header = TRUE,
                              sep = '\t')

fem_df$percentage <- fem_df$number_of_GFP_kernels / (fem_df$number_of_GFP_kernels + fem_df$number_of_WT_kernels)

new_df$percentage <- new_df$number_of_GFP_kernels / (new_df$number_of_GFP_kernels + new_df$number_of_WT_kernels)

old_df$percentage <- old_df$number_of_GFP_kernels / (old_df$number_of_GFP_kernels + old_df$number_of_WT_kernels)

fem_df1 <- fem_df %>% select(name, allele, Hand_or_Model, percentage, year)
old_df1 <- old_df %>% select(name, allele, Hand_or_Model, percentage, year)
new_df1 <- new_df %>% select(name, allele, Hand_or_Model, percentage, year)

c_data <- rbind(fem_df1, old_df1)

```

```{r}
c_data %>%
  group_by(Hand_or_Model) %>%
  summarize(avg_per = mean(percentage), count = n())

old_df %>%
  group_by(Hand_or_Model, year) %>%
  #group_by(year) %>%
  summarize(avg_per = mean(percentage), count = n()) #think about removing 2020 data

fem_df %>%
  group_by(Hand_or_Model) %>%
  summarize(avg_per = mean(percentage), count = n())
```

```{r}
t.test(percentage ~ Hand_or_Model, data = old_df, alternative = "two.sided")
#there could be a systematic bias
#if all the significant alleles were counted by hand... dragging the overall average down. (can look into more) <- can remove these alleles and do the analysis again
#non-random bias in the computer model, using computer model for 2018-2019 data, else is hand-counted 
```

```{r}
t.test(percentage ~ Hand_or_Model, data = c_data, alternative = "less")
```

```{r}
c_data1 <- c_data %>% filter(year != "2020")

t.test(percentage ~ Hand_or_Model, data = c_data1, alternative = "less")
```

```{r}
t.test(percentage ~ Hand_or_Model, data = fem_df, alternative = "two.sided")
#confidence in the system. no diff between computer vision and person.
#if there was a difference, more in the female data set.
#expect more undercount in the female side
```

```{r}
fem_df2 <- fem_df1 %>% filter(year != "2020")

t.test(percentage ~ Hand_or_Model, data = fem_df, alternative = "two.sided")
```

```{r}
old_df2 <- old_df1 %>% filter(year != "2020")

t.test(percentage ~ Hand_or_Model, data = old_df2, alternative = "two.sided")
```
