---
title: "Handler Effect"
author: "Michelle Bang"
date: '2022-10-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
```

```{r}
data <- read.table(file = "TransmissionDataExtended_forMichelle_Set1_Male_Oct22.xlsx - All_male_data_18192021.tsv",
                   header = TRUE,
                   sep = "\t")
```

```{r}
data$percentage <- data$number_of_GFP_kernels / (data$number_of_GFP_kernels + data$number_of_WT_kernels)
data$totalkernels <- data$number_of_GFP_kernels + data$number_of_WT_kernels
```

```{r}
data <- data %>%
  mutate(pollen_handler = if_else(pollen_handler == 0, "?", pollen_handler))
```


```{r}
data %>%
  group_by(pollen_handler) %>%
  summarize(avg_per = mean(percentage), count = n())
```
```{r}
data %>%
  group_by(pollen_handler, year) %>%
  summarize(avg_per = mean(percentage), count = n())
```
```{r}
data %>%
  filter(year == 2018) %>%
  group_by(pollen_handler) %>%
  summarize(avg_per = mean(percentage), count = n())
```
```{r}
data %>%
  filter(year == 2019) %>%
  group_by(pollen_handler) %>%
  summarize(avg_per = mean(percentage), count = n())
```

```{r}
data %>%
  filter(year == 2020) %>%
  group_by(pollen_handler) %>%
  summarize(avg_per = mean(percentage), count = n())
```

```{r}
data %>%
  filter(year == 2021) %>%
  group_by(pollen_handler) %>%
  summarize(avg_per = mean(percentage), count = n())
```

```{r}
data %>%
  group_by(allele) %>%
  summarize(count = n()) %>%
  arrange(desc(count))
```
```{r}
data %>%
  group_by(allele, pollen_handler) %>%
  summarize(count = n()) %>%
  arrange(desc(count))
```
```{r}
data %>%
  group_by(allele, pollen_handler) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  filter(allele == "R84A12")
```

```{r}
data %>%
  group_by(allele, pollen_handler) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  filter(allele == "R96B12")
```

```{r}
data %>%
  group_by(allele, pollen_handler) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  filter(allele == "R96C12")
```

```{r}
# has only one handler
data %>%
  group_by(allele, pollen_handler) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  filter(allele == "R106E07")
```
```{r}
ggplot(data = data, mapping = aes(x = allele, y = percentage, color = pollen_handler)) +
  geom_point()
```

```{r}
ggplot(data = data, mapping = aes(x = pollen_handler, y = percentage, color = allele)) +
  geom_point()
```

```{r}
data %>%
  group_by(allele) %>%
  summarize(mean_kernel = mean(totalkernels)) %>%
  arrange(desc(mean_kernel))
```
```{r}
data %>%
  group_by(allele) %>%
  summarize(mean_wtkernel = mean(number_of_WT_kernels)) %>%
  arrange(desc(mean_wtkernel))
```

```{r}
data %>%
  group_by(allele) %>%
  summarize(mean_gfpkernel = mean(number_of_GFP_kernels)) %>%
  arrange(desc(mean_gfpkernel))
```
```{r}
# linear model for one allele (R84A12)
# had handler ?, H, J, M, Z
data2 <- data %>%
  filter(allele =="R84A12")
modR84A12 <- lm(percentage ~ pollen_handler, data2)
summary(modR84A12)
```
```{r}
# linear model for one allele (R84A12)
# looking at totalkernels
data2 <- data %>%
  filter(allele =="R84A12")
mod2R84A12 <- lm(percentage ~ totalkernels, data2)
summary(mod2R84A12)
```
```{r}
#R96B12
# J, Z and ?
data2 <- data %>%
  filter(allele =="R96B12")
modR96B12 <- lm(percentage ~ pollen_handler, data2)
summary(modR96B12)
```
```{r}
#R96B12
# J and Z only
# very low r-square values
data2 <- data %>%
  filter(allele =="R96B12") %>%
  filter(pollen_handler != "?")
modR96B12 <- lm(percentage ~ pollen_handler, data2)
summary(modR96B12)
```


```{r}
# linear model for one allele (R106E07)
# one handler, but had the most kernels
# this one was not found to be significant in prev analysis
data2 <- data %>%
  filter(allele =="R106E07")
modR106E07 <- lm(percentage ~ totalkernels, data2)
summary(modR106E07)
```
