---
title: "Separate All Pollen Spatial Analysis for Paper"
author: "Michelle Bang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Part 0: Loading all of my files and functions

```{r}
source("../LabWorkNathan-master/R/xml_to_coordinates.R")
source("../LabWorkNathan-master/R/coordinates_to_xbins.R")
source("../LabWorkNathan-master/R/xml_to_coord_edited.R")
library(ggplot2)
library(tidyverse)
library(ggpubr)
```

```{r}
library(qvalue)
```

```{r}
xml_to_coord <- function(input_data_path){
  #print(input_data_path) #this is to check which files are able to be read.
  if (grepl("\\_inference.xml", input_data_path)){
    xml_to_coordinates2(input_data_path)
  } else{
    xml_to_coordinates(input_data_path)
  }
}
```

```{r}
new_df <- read.table(file = "../../AllEarKernelCountData_MichellePaper.tsv",
                              header = TRUE,
                              sep = '\t', na.strings = c("", " ", NA))
```

```{r}
male_df <- new_df[new_df$cross_type == "Pollen",]
female_df <- new_df[new_df$cross_type == "Ear",]
```

```{r}
glm_df <- read.table(file = "../../2024_male_analysis_sum.tsv",
                              header = TRUE,
                              sep = '\t', na.strings = c("", " ", NA))
```


```{r}
sig_names <- male_df %>%
  filter(allele == "R04A02" | 
           allele == "R102H01" | 
           allele == "R33F03" | 
           allele == "R49F11" |				
           allele == "R67C09" |
           allele == "R82A03" |
           allele == "R82C05" |
           allele == "R84A12" |
           allele == "R89B08" |
           allele == "R92F08" |
           allele == "R95D10" |
           allele == "R96C12") %>%
  select(name)
```

```{r}
#load file names based on your folder
filenamesload = list.files("/Users/michellebang/st research lab/spatialanalysis/SpatialAnalysisMichelle/all_pollen_xml", pattern="*.xml", full.names=TRUE)
```


```{r}
filenames <- c()
for (i in 1:length(filenamesload)){
  for (j in 1:nrow(sig_names)){
    if (grepl(sig_names$name[[j]], filenamesload[[i]])){
      filenames <- append(filenames, filenamesload[[i]])
      break
    }
  }
}
```

```{r}
#Creating a list of file names to keep track of. 
titleList <- as.list(basename(filenames))
```

```{r}
#Directly creating a vector of the file names
title_vec <- vector(length = length(filenames))

for (i in 1:length(filenames)){
  title_vec[i] <- basename(filenames)[[i]]
}
```

```{r}
truePVal = data.frame(matrix(ncol = 2)) 
colnames(truePVal) <- c("Linear Ends", "Quad Ends")
```

```{r}
#megaDf = data.frame()
```

```{r}
coords = lapply(filenames, xml_to_coord)

  #Removes faulty xml from the files. 

sequence = rev(seq(1:length(coords)))

#Checks if there will be an error when coordinates_to_xbins runs. If there is, it removes it from filenames 
for (i in sequence) {
  if (nrow(coords[[i]]) == 0)  {
    filenames = filenames[-i]
    title_vec = title_vec[-i]
  }
}
```

```{r}
#The 0 observation issue is caused by files that don't use 1 and 2 as their marker numbers which is a requirement for xml_to_coordinates
bin_data = lapply(coords, function(x) {coordinates_to_xbins(x,16)} )

sequence = rev(seq(1:length(bin_data)))

#Removes the files that break the glm, namely the ears with only one kind of kernel allele. At most removes the cases with very few WT or GFP which are by definition odd ears. 

for (i in sequence) {
  sumWT = sum(bin_data[[i]]$WT)
  sumGFP = sum(bin_data[[i]]$GFP)
    if ((sumWT < 5) | (sumGFP < 5)) {
      bin_data = bin_data[-i]
      filenames = filenames[-i]
      title_vec = title_vec[-i]
    }
}

#The 0 observation issue is caused by files that don't use 1 and 2 as their marker numbers which is a requirement for xml_to_coordinates
full_data = lapply(coords, function(x) {coordinates_to_xbins(x,1)} )

sequence = rev(seq(1:length(full_data)))

#Removes the files that break the glm, namely the ears with only one kind of kernel allele. At most removes the cases with very few WT or GFP which are by definition odd ears. 

for (i in sequence) {
  sumWT = sum(full_data[[i]]$WT)
  sumGFP = sum(full_data[[i]]$GFP)
    if ((sumWT < 5) | (sumGFP < 5)) {
      full_data = full_data[-i]
    }
}


TransmissionRate <- c()
for (i in 1:length(filenames)) {
  TransmissionRate <- append(TransmissionRate, full_data[[i]]$GFP/(full_data[[i]]$GFP + full_data[[i]]$WT))
}

TotalKernelFull <- c()
for (i in 1:length(filenames)) {
  TotalKernelFull <- append(TotalKernelFull, full_data[[i]]$GFP + full_data[[i]]$WT)
}

#Start chopping off the ends
sequence = seq(1,length(bin_data))

#Creating an empty list
bin_ed = list()

for (i in sequence) {
    bin_ed[[i]] = data.frame("bins" = bin_data[[i]]$bins[2:15], "WT" = bin_data[[i]]$WT[2:15] , "GFP" = bin_data[[i]]$GFP[2:15])
}

TotalKernelEnds <- c()
for (i in 1:length(filenames)) {
  TotalKernelEnds <- append(TotalKernelEnds, sum(bin_ed[[i]]$GFP) + sum(bin_ed[[i]]$WT))
}

#Turn the data into a glm
ends_glm_data = lapply(bin_ed, function(x) {glm(cbind(GFP,WT) ~ bins,family = quasibinomial(link = "logit"), data = x)})


#Extract the p values
ends_pv_data = lapply(ends_glm_data, function(x) {(summary(x)$coefficients)})

ends_p_data = lapply(ends_pv_data, function(x) {x[8]})

#Comment this out to look at the non adjusted values, you can swap the method by changing 'method = fdr'
adj_p_data = p.adjust(ends_p_data,method = "fdr")

adj_p_df <- data.frame(matrix(unlist(adj_p_data), nrow=length(adj_p_data), byrow=T))
names(adj_p_df)[names(adj_p_df) == colnames(adj_p_df[1])] = "adj_p_value"

ends_p_df <- data.frame(matrix(unlist(ends_p_data), nrow=length(ends_p_data), byrow=T))
names(ends_p_df)[names(ends_p_df) == colnames(ends_p_df[1])] = "p_value"

endsfullDf = cbind(title_vec, ends_p_df)
colnames(endsfullDf[1]) = "Name"
endsfullDf <- cbind(endsfullDf, TransmissionRate)
endsfullDf <- cbind(endsfullDf, adj_p_df)

#Uncomment to save data for just linear term as .tsv
#endsfullDf1 = as.matrix(endsfullDf)
#write.table(endsfullDf1, file = paste0(filenames,"_glm_ends.tsv"), sep = "\t", row.names=FALSE)

# TEST FOR PROP OF TRUE NULL P-VALUES

#Another way of accounting for multiple testing
#Should give out percentage of null p-values (we are interested in 1-nullper)
per_adj_p_data = pi0est(unlist(ends_p_data)) 
trueProp = 1-per_adj_p_data$pi0 
truePVal[1] = trueProp


#ANOVA Testing for quadratic term

#First part of set up should be the same as GLM with ends chopped off.


bins_squared_ends = bin_ed
bin_sq_data_ends = bin_ed

sequence = seq(1, length(bin_ed))
sequence2  = seq(1, 14)

for (i in sequence) {
  for (j in sequence2) {
  bins_squared_ends[[i]]$bins[j] = (bin_sq_data_ends[[i]]$bins[j])^2
  }
  bin_sq_data_ends[[i]] = data.frame(bin_sq_data_ends[[i]],bins_squared_ends[[i]]$bins)
}

#Turn the data into a glm
#If this breaks just double check how R is naming the bin_squared column of bin_data and replace "bins_squared..i...bins" with that
sq_glm_data_ends = lapply(bin_sq_data_ends, function(x) {glm(cbind(GFP,WT) ~ bins + bins_squared_ends..i...bins,family = quasibinomial(link = "logit"), data = x)})

#Creating null model
null_ends_model <- lapply(bin_ed, function(x) {glm(cbind(GFP,WT) ~ 1,family = quasibinomial(link = "logit"), data = x)})


#Setting up empty list
anova_ends_data <- vector(length = length(bin_ed))

for (i in 1:length(bin_ed)){
  anova_ends_data[i] <- anova(null_ends_model[[i]], sq_glm_data_ends[[i]], test = "F")$"Pr(>F)"[2]
}

anova_ends_df <- as.data.frame(anova_ends_data)
row.names(anova_ends_df) <- 1:length(bin_ed)
adj_anova = p.adjust(anova_ends_data, method = "fdr")
colnames(anova_ends_df)[1] = "p_value_sq"
#Uncomment for when you want to add column for names.
#anova_ends_df <- cbind(anova_ends_df, titleDf)
#colnames(anova_ends_df)[2] = "name"
anova_ends_df <- cbind(anova_ends_df, adj_anova)
colnames(anova_ends_df)[2] = "adj_p_value_sq"

#Uncomment if you want to save just ANOVA data as .tsv
#write.table(anova_ends_df, file = paste0(filenames[[n]][[1]],"_anova_ends.tsv"), sep = "\t", row.names=FALSE) 

# TEST FOR PROP OF TRUE NULL P-VALUES

#Another way of accounting for multiple testing
#Should give out percentage of null p-values (we are interested in 1-nullper)
per_adj_anova = pi0est(unlist(anova_ends_data)) 
truePropA = 1-per_adj_anova$pi0 
truePVal[2] = truePropA

endsfullDf <- cbind(endsfullDf, anova_ends_df)
endsfullDf <- cbind(endsfullDf, TotalKernelFull)
endsfullDf <- cbind(endsfullDf, TotalKernelEnds)
```

```{r}
ordered_df <- endsfullDf %>%
  arrange(p_value)
```

```{r}
write.table(ordered_df, file = "sig_pollen_spatial_analysis.tsv", sep = "\t", row.names=FALSE)
```

```{r}
write.table(truePVal, file = "sig_pollen_true_prop_optimized.tsv", sep = "\t", row.names=FALSE)
```

----

Non-Significant Alleles

```{r}
filenames <- c()
for (i in 1:length(filenamesload)){
  add = FALSE
  for (j in 1:nrow(sig_names)){
    if (grepl(sig_names$name[[j]], filenamesload[[i]])){
      add = FALSE
      break
    } else {
      add = TRUE
    }
  }
  if (add) {
    filenames <- append(filenames, filenamesload[[i]])
  }
}
```

```{r}
#Creating a list of file names to keep track of. 
titleList <- as.list(basename(filenames))
```

```{r}
#Directly creating a vector of the file names
title_vec <- vector(length = length(filenames))

for (i in 1:length(filenames)){
  title_vec[i] <- basename(filenames)[[i]]
}
```

```{r}
truePVal = data.frame(matrix(ncol = 2)) 
colnames(truePVal) <- c("Linear Ends", "Quad Ends")
```

```{r}
#megaDf = data.frame()
```

```{r}
coords = lapply(filenames, xml_to_coord)

  #Removes faulty xml from the files. 

sequence = rev(seq(1:length(coords)))

#Checks if there will be an error when coordinates_to_xbins runs. If there is, it removes it from filenames 
for (i in sequence) {
  if (nrow(coords[[i]]) == 0)  {
    filenames = filenames[-i]
    title_vec = title_vec[-i]
  }
}
```

```{r}
#The 0 observation issue is caused by files that don't use 1 and 2 as their marker numbers which is a requirement for xml_to_coordinates
bin_data = lapply(coords, function(x) {coordinates_to_xbins(x,16)} )

sequence = rev(seq(1:length(bin_data)))

#Removes the files that break the glm, namely the ears with only one kind of kernel allele. At most removes the cases with very few WT or GFP which are by definition odd ears. 

for (i in sequence) {
  sumWT = sum(bin_data[[i]]$WT)
  sumGFP = sum(bin_data[[i]]$GFP)
    if ((sumWT < 5) | (sumGFP < 5)) {
      bin_data = bin_data[-i]
      filenames = filenames[-i]
      title_vec = title_vec[-i]
    }
}

#The 0 observation issue is caused by files that don't use 1 and 2 as their marker numbers which is a requirement for xml_to_coordinates
full_data = lapply(coords, function(x) {coordinates_to_xbins(x,1)} )

sequence = rev(seq(1:length(full_data)))

#Removes the files that break the glm, namely the ears with only one kind of kernel allele. At most removes the cases with very few WT or GFP which are by definition odd ears. 

for (i in sequence) {
  sumWT = sum(full_data[[i]]$WT)
  sumGFP = sum(full_data[[i]]$GFP)
    if ((sumWT < 5) | (sumGFP < 5)) {
      full_data = full_data[-i]
    }
}


TransmissionRate <- c()
for (i in 1:length(filenames)) {
  TransmissionRate <- append(TransmissionRate, full_data[[i]]$GFP/(full_data[[i]]$GFP + full_data[[i]]$WT))
}

TotalKernelFull <- c()
for (i in 1:length(filenames)) {
  TotalKernelFull <- append(TotalKernelFull, full_data[[i]]$GFP + full_data[[i]]$WT)
}

#Start chopping off the ends
sequence = seq(1,length(bin_data))

#Creating an empty list
bin_ed = list()

for (i in sequence) {
    bin_ed[[i]] = data.frame("bins" = bin_data[[i]]$bins[2:15], "WT" = bin_data[[i]]$WT[2:15] , "GFP" = bin_data[[i]]$GFP[2:15])
}

TotalKernelEnds <- c()
for (i in 1:length(filenames)) {
  TotalKernelEnds <- append(TotalKernelEnds, sum(bin_ed[[i]]$GFP) + sum(bin_ed[[i]]$WT))
}

#Turn the data into a glm
ends_glm_data = lapply(bin_ed, function(x) {glm(cbind(GFP,WT) ~ bins,family = quasibinomial(link = "logit"), data = x)})


#Extract the p values
ends_pv_data = lapply(ends_glm_data, function(x) {(summary(x)$coefficients)})

ends_p_data = lapply(ends_pv_data, function(x) {x[8]})

#Comment this out to look at the non adjusted values, you can swap the method by changing 'method = fdr'
adj_p_data = p.adjust(ends_p_data,method = "fdr")

adj_p_df <- data.frame(matrix(unlist(adj_p_data), nrow=length(adj_p_data), byrow=T))
names(adj_p_df)[names(adj_p_df) == colnames(adj_p_df[1])] = "adj_p_value"

ends_p_df <- data.frame(matrix(unlist(ends_p_data), nrow=length(ends_p_data), byrow=T))
names(ends_p_df)[names(ends_p_df) == colnames(ends_p_df[1])] = "p_value"

endsfullDf = cbind(title_vec, ends_p_df)
colnames(endsfullDf[1]) = "Name"
endsfullDf <- cbind(endsfullDf, TransmissionRate)
endsfullDf <- cbind(endsfullDf, adj_p_df)

#Uncomment to save data for just linear term as .tsv
#endsfullDf1 = as.matrix(endsfullDf)
#write.table(endsfullDf1, file = paste0(filenames,"_glm_ends.tsv"), sep = "\t", row.names=FALSE)

# TEST FOR PROP OF TRUE NULL P-VALUES

#Another way of accounting for multiple testing
#Should give out percentage of null p-values (we are interested in 1-nullper)
per_adj_p_data = pi0est(unlist(ends_p_data)) 
trueProp = 1-per_adj_p_data$pi0 
truePVal[1] = trueProp


#ANOVA Testing for quadratic term

#First part of set up should be the same as GLM with ends chopped off.


bins_squared_ends = bin_ed
bin_sq_data_ends = bin_ed

sequence = seq(1, length(bin_ed))
sequence2  = seq(1, 14)

for (i in sequence) {
  for (j in sequence2) {
  bins_squared_ends[[i]]$bins[j] = (bin_sq_data_ends[[i]]$bins[j])^2
  }
  bin_sq_data_ends[[i]] = data.frame(bin_sq_data_ends[[i]],bins_squared_ends[[i]]$bins)
}

#Turn the data into a glm
#If this breaks just double check how R is naming the bin_squared column of bin_data and replace "bins_squared..i...bins" with that
sq_glm_data_ends = lapply(bin_sq_data_ends, function(x) {glm(cbind(GFP,WT) ~ bins + bins_squared_ends..i...bins,family = quasibinomial(link = "logit"), data = x)})

#Creating null model
null_ends_model <- lapply(bin_ed, function(x) {glm(cbind(GFP,WT) ~ 1,family = quasibinomial(link = "logit"), data = x)})


#Setting up empty list
anova_ends_data <- vector(length = length(bin_ed))

for (i in 1:length(bin_ed)){
  anova_ends_data[i] <- anova(null_ends_model[[i]], sq_glm_data_ends[[i]], test = "F")$"Pr(>F)"[2]
}

anova_ends_df <- as.data.frame(anova_ends_data)
row.names(anova_ends_df) <- 1:length(bin_ed)
adj_anova = p.adjust(anova_ends_data, method = "fdr")
colnames(anova_ends_df)[1] = "p_value_sq"
#Uncomment for when you want to add column for names.
#anova_ends_df <- cbind(anova_ends_df, titleDf)
#colnames(anova_ends_df)[2] = "name"
anova_ends_df <- cbind(anova_ends_df, adj_anova)
colnames(anova_ends_df)[2] = "adj_p_value_sq"

#Uncomment if you want to save just ANOVA data as .tsv
#write.table(anova_ends_df, file = paste0(filenames[[n]][[1]],"_anova_ends.tsv"), sep = "\t", row.names=FALSE) 

# TEST FOR PROP OF TRUE NULL P-VALUES

#Another way of accounting for multiple testing
#Should give out percentage of null p-values (we are interested in 1-nullper)
per_adj_anova = pi0est(unlist(anova_ends_data)) 
truePropA = 1-per_adj_anova$pi0 
truePVal[2] = truePropA

endsfullDf <- cbind(endsfullDf, anova_ends_df)
endsfullDf <- cbind(endsfullDf, TotalKernelFull)
endsfullDf <- cbind(endsfullDf, TotalKernelEnds)
```

```{r}
ordered_df <- endsfullDf %>%
  arrange(p_value)
```

```{r}
write.table(ordered_df, file = "nonsig_pollen_spatial_analysis.tsv", sep = "\t", row.names=FALSE)
```

```{r}
write.table(truePVal, file = "nonsig_pollen_true_prop_point_optimized.tsv", sep = "\t", row.names=FALSE)
```




